### ISSUE TITLE
realoc() instead of MAX_SAMPLE definition

### ISSUE THREAD

**Issue by brainstorm** [yne/vcd#13]
As discussed on https://github.com/yne/vcd/issues/11#issuecomment-1018996599, it would be nice that vcd does not care too much about the file size(s) of .vcd.

IMHO the visualization is not important (vertical vs horizontal), but I'd like to open those files transparently without getting errors or having to count lines and define MAX_SAMPLE accordingly.

**Comment by yne** [comment]
I've made a (naive) `realloc()` version of vcd (see: https://github.com/yne/vcd/commit/fa95131bf67dafb0d2b5f0643d0451d0e8d417f3)
but the new parsing speed is 47x slower.

```
time ./vcd_static < samples/libsigrok.vcd >/dev/null

real    0m0.063s
user    0m0.043s
sys     0m0.020s
```

```
time ./vcd_realloc < samples/libsigrok.vcd >/dev/null

real    0m3.001s
user    0m2.899s
sys     0m0.060s
```

I'll try to find a clever (i.e. less maintainable) way of `realloc()`

Edit: Fixed
