### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [yne/vcd#20]
Would you like to add more error handling for return values from functions like the following?
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [printYml](https://github.com/yne/vcd/blob/f2b1627c6bf2f3ba8f4c379205a205085fc5f742/vcd.c#L173)
* [realloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Memory allocation") ⇒ [parseVcdTimestamp](https://github.com/yne/vcd/blob/f2b1627c6bf2f3ba8f4c379205a205085fc5f742/vcd.c#L116)

**Comment by yne** [comment]
because the lack of return value handling generate warning ?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by yne** [comment]
even `-Wall -Wpedantic -Wextra` does not throw any warning about missing return value handling

How did you get those warnings ?

**Comment by yne** [comment]
@elfring judging by the high number of issue you create, I suspect you to be some kind of clang-tidy bot.

Can you confirm/infirm so I can report you ?

**Comment by elfring** [comment]
:thought_balloon: I am just another software developer and source code reviewer who got used to [pointing known programming weaknesses and mistakes out](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions#EXP12C.Donotignorevaluesreturnedbyfunctions-AutomatedDetection "Do not ignore values returned by functions") for further considerations.

**Comment by elfring** [comment]
* :thinking: How do you think about to avoid that this software [depends on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers")?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by yne** [comment]
what ?

**Comment by elfring** [comment]
:thought_balloon: How much do you understand advices from linked information sources?

**Comment by yne** [comment]
Your advice makes no senses: nobody read the return value of a `printf` call.

Your lack of contextual awareness is a proof of your inability to give any advice.

I'll ask one last time before reporting you : How did you found about those `ignorance of return value` ? And how did you activate those warning in your compiler ?

You better have a precise response this time. I'm [ready](https://support.github.com/contact/report-abuse?category=report-abuse&report=elfring&report_id=660477&report_type=user) :)

> During the past 2 weeks, this user have been spamming many repository with irrelevant  "code advice" and seems unable to answer basic human questions which suggest that this user might be an automated code-bot.

**Comment by elfring** [comment]
>Your advice makes no senses:

It seems to be occasionally challenging to achieve consensus on mentioned software details.


>nobody read the return value of a printf call.

I got other impressions.

:thought_balloon: Would you like to test the discussed programs also with a device like “[/dev/full](https://en.wikipedia.org/wiki//dev/full "Documentation")”?

Can you care more for consequences from failed memory allocations?


>How did you found about those `ignorance of return value`?

I found the reported programming mistakes just by [using the GitHub source code search interface](https://docs.github.com/en/search-github/searching-on-github/searching-code "Searching code").


>You better have a precise response this time.

I find my code advices relevant for various software components.

**Comment by yne** [comment]
Thank you for your feedback

I took your advice in https://github.com/yne/vcd/commit/8c5455fd09a32819f9a77695f5508c14f4329d15
