### ISSUE TITLE
which terminal viewer are you using?

### ISSUE THREAD

**Issue by Kreijstal** [yne/vcd#21]
I am in mint and get things like this,

![image](https://github.com/yne/vcd/assets/2415206/169f5b5d-2f3e-4a59-994d-65bc17cffda6)

So it is not ideal

**Comment by Kreijstal** [comment]
it seems less was the problem, if I pipe it into a file and view the file with neovim there is no problem... but damn, I wanted to do it dynamically, shame

**Comment by yne** [comment]
So running `./vcd < samples/plasma.vcd | less -S` does not offer you a trunkated/scrollable view ?

Here is my setup:
```
> less --version
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman
```

And it work as expected
![image](https://github.com/yne/vcd/assets/5113053/378fbb9a-47eb-41df-80a7-d28d2f2281f3)

**Comment by Kreijstal** [comment]
maybe it's my enviromental variables?
```
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```
alright I fixed it.
I was using `less -r -S`, because previously I didn't have a good language
output of `less -S`:
![image](https://github.com/yne/vcd/assets/2415206/d557a08f-9128-4578-85be-7b6e938862a2)
but I generated a utf8 locale
```
echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
```

and it works. So okay, I see now
